import { FilterByStatusPipe } from './filter-by-status.pipe';



describe('FilterByStatusPipe', () => {
  it('create an instance', () => {
    const pipe = new FilterByStatusPipe();
    expect(pipe).toBeTruthy();
  });

  it('Filter array of objects by status', () => {
    const pipe = new FilterByStatusPipe();
    const option = "I";
    const fund_list = [
      {
        "maximum_initial_subscription_amount_str": "999,999,999,999.00",
        "close_date": "17 Mar 2022",
        "three_month_ind": "EQUAL",
        "switch_indicator": "Y",
        "fund_document": [
          {
            "msId": 10724,
            "fundCode": "BHL17D",
            "msLink": "F000000AP0",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000AP0&documenttype=1&investmenttype=1",
            "isActive": "Y",
            "docId": 1,
            "startDate": "2021-07-01T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Master Prospectus",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 10725,
            "fundCode": "BHL17D",
            "msLink": "F000000AP0",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000AP0&documenttype=77&investmenttype=1",
            "isActive": "Y",
            "docId": 77,
            "startDate": "2021-07-01T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Product Highlight Sheet",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 10726,
            "fundCode": "BHL17D",
            "msLink": "F000000AP0",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000AP0&documenttype=4&investmenttype=1",
            "isActive": "Y",
            "docId": 4,
            "startDate": "2021-08-31T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Annual Report",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 10727,
            "fundCode": "BHL17D",
            "msLink": "F000000AP0",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000AP0&documenttype=5&investmenttype=1",
            "isActive": "Y",
            "docId": 5,
            "startDate": "2021-02-28T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Semi-Annual Report",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 10728,
            "fundCode": "BHL17D",
            "msLink": "F000000AP0",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000AP0&documenttype=52&investmenttype=1",
            "isActive": "Y",
            "docId": 52,
            "startDate": "2021-10-31T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Fact sheet",
            "modifiedDate": "2021-12-31T16:40:01"
          }
        ],
        "fund_code": "BHL17D",
        "risk_rating": "2",
        "minimum_initial_subscription_amount": 2000,
        "maximum_subsequent_subscription_amount": 999999999999,
        "manager_code": "BHL",
        "sales_charge_staff": 0,
        "minimum_initial_subscription_amount_str": "2,000.00",
        "class_name": "FIXED INCOME",
        "min_holding": 1000,
        "minimum_subsequent_subscription_amount_str": "500.00",
        "current_holding": "N",
        "min_redem_amt": 500,
        "fund_status": "I",
        "class_seq": 2,
        "maximum_initial_subscription_amount": 999999999999,
        "fund_name": "Cimb Islamic Sukuk Fund",
        "one_month_ind": "EQUAL",
        "fund_indicator": "I",
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "0.00",
        "one_month": "0.00",
        "max_redem_amt": 999999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
        "nav_price": 1.2863,
        "min_switch_amt": 500,
        "risk_name": "Defensive",
        "product_category": "FIX_ INCOME ",
        "minimum_subsequent_subscription_amount": 500,
        "sales_charge_nonstaff": 0
      },
      {
        "maximum_initial_subscription_amount_str": "999,999,999,999.00",
        "close_date": "21 Mar 2022",
        "three_month_ind": "EQUAL",
        "switch_indicator": "Y",
        "fund_document": [
          {
            "msId": 11054,
            "fundCode": "BHL15F",
            "msLink": "F000000APG",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
            "isActive": "Y",
            "docId": 1,
            "startDate": "2021-06-25T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Master Prospectus",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 11055,
            "fundCode": "BHL15F",
            "msLink": "F000000APG",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
            "isActive": "Y",
            "docId": 77,
            "startDate": "2021-06-25T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Product Highlight Sheet",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 11056,
            "fundCode": "BHL15F",
            "msLink": "F000000APG",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
            "isActive": "Y",
            "docId": 4,
            "startDate": "2021-08-31T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Annual Report",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 11057,
            "fundCode": "BHL15F",
            "msLink": "F000000APG",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
            "isActive": "Y",
            "docId": 5,
            "startDate": "2021-02-28T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Semi-Annual Report",
            "modifiedDate": "2021-12-31T16:40:01"
          },
          {
            "msId": 11058,
            "fundCode": "BHL15F",
            "msLink": "F000000APG",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
            "isActive": "Y",
            "docId": 52,
            "startDate": "2021-10-31T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Fact sheet",
            "modifiedDate": "2021-12-31T16:40:01"
          }
        ],
        "fund_code": "BHL15F",
        "risk_rating": "0",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 999999999999,
        "manager_code": "BHL",
        "sales_charge_staff": 0,
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 0,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "N",
        "min_redem_amt": 0,
        "fund_status": "A",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 999999999999,
        "fund_name": "Cimb-Principal Deposit Fund",
        "one_month_ind": "EQUAL",
        "fund_indicator": "C",
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "0.00",
        "one_month": "0.00",
        "max_redem_amt": 999999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
        "nav_price": 1,
        "min_switch_amt": 0,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000,
        "sales_charge_nonstaff": 0
      }
    ];
    const filtered_funds = [
      {
        "maximum_initial_subscription_amount_str": "9,999,999,999.00",
        "close_date": "21 Mar 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 10814,
                "fundCode": "CBT35F",
                "msLink": "F000005GIT",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 10815,
                "fundCode": "CBT35F",
                "msLink": "F000005GIT",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 10816,
                "fundCode": "CBT35F",
                "msLink": "F000005GIT",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2021-01-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 10817,
                "fundCode": "CBT35F",
                "msLink": "F000005GIT",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-07-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 10818,
                "fundCode": "CBT35F",
                "msLink": "F000005GIT",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "CBT35F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 9999999999,
        "manager_code": "CBT",
        "sales_charge_staff": 0,
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 5000,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "N",
        "min_redem_amt": 5000,
        "fund_status": "A",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 9999999999,
        "fund_name": "Cimb Islamic Deposit Fund",
        "one_month_ind": "DOWN",
        "fund_indicator": "I",
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "-0.37",
        "one_month": "-0.37",
        "max_redem_amt": 9999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
        "nav_price": 0.9999,
        "min_switch_amt": 5000,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000,
        "sales_charge_nonstaff": 0
    },
    {
        "maximum_initial_subscription_amount_str": "9,999,999,999.00",
        "close_date": "11 May 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 11019,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11020,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11021,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2020-11-30T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11022,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-05-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11023,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "CBT26F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 9999999999,
        "manager_code": "CBT",
        "sales_charge_staff": 0,
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 5000,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "N",
        "min_redem_amt": 1000,
        "fund_status": "A",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 9999999999,
        "fund_name": "Cimb Islamic Money Market Fund",
        "one_month_ind": "EQUAL",
        "fund_indicator": "I",
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "-6.73",
        "one_month": "0.00",
        "max_redem_amt": 9999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
        "nav_price": 1.0001,
        "min_switch_amt": 1000,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000,
        "sales_charge_nonstaff": 0
    }
    ];

    if(option === "I") {
      fund_list.filter(data => {
        return data.fund_indicator === option
      })
    } else {
      return fund_list;
    }
    expect(pipe.transform(fund_list, "I","Y")).toBeTruthy();
    expect(pipe.transform(fund_list, "","")).toBeTruthy();
  })

});
