export interface Setting {
    description: string;
    enabled: boolean;
    utSettingId: string;
    utSettingGroupId: string;
}

export enum SettingsUid {
    ADD_NEW_INVESTMENT_AT_INVESTMENT_DASHBOARD = "001",
    ADD_TO_CART_AT_INVESTMENT_DASHBOARD_FOR_TOPUP = "002",
    ADD_TO_CART_AT_FUND_DETAIL_PAGE_FOR_PURCHASE = "003",
    ADD_TO_CART_AT_FUND_DETAIL_PAGE_FOR_TOPUP = "004",
    PURCHASE_TRANSACTION_IN_CART = "005",
    REDEEM_AT_INVESTMENT_DASHBOARD = "006",
    REDEEM_AT_FUND_DETAILS = "007",
    REDEEM_TRANSACTION_AT_CART = "008",
    SWITCH_AT_INVESTMENT_DASHBOARD = "009",
    SWITCH_AT_FUND_DETAILS = "010",
    SWITCH_TRANSACTION_AT_CART = "011",
    REDO_RISK_PROFILING_AT_INVESTMENT_DASHBOARD = "012",
    LEARN_MORE_AT_INVESTMENT_DASHBOARD = "013",
    APPLY_NOW_AT_MYINVETMENT_DASHBOARD = "014"
}