import { ComponentFixture, TestBed } from '@angular/core/testing';
import { MatBottomSheetModule } from '@angular/material/bottom-sheet';
import { MatDialogModule, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatSort, MatSortModule } from '@angular/material/sort';
import { MatPaginatorModule } from '@angular/material/paginator'
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterTestingModule } from '@angular/router/testing';
import * as exp from 'constants';

import { DialogFundsComponent } from './dialog-funds.component';


const dialogMock = {
  close: () => { 
    //test
   }
};

const fundObj =  {
    "maximum_initial_subscription_amount_str": "9,999,999,999.00",
    "close_date": "21 Mar 2022",
    "three_month_ind": "DOWN",
    "switch_indicator": "Y",
    "fund_document": [
        {
            "msId": 10814,
            "fundCode": "CBT35F",
            "msLink": "F000005GIT",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=1&investmenttype=1",
            "isActive": "Y",
            "docId": 1,
            "startDate": "2021-07-01T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Master Prospectus",
            "modifiedDate": "2021-12-31T16:40:01"
        },
        {
            "msId": 10815,
            "fundCode": "CBT35F",
            "msLink": "F000005GIT",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=77&investmenttype=1",
            "isActive": "Y",
            "docId": 77,
            "startDate": "2021-07-01T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Product Highlight Sheet",
            "modifiedDate": "2021-12-31T16:40:01"
        },
        {
            "msId": 10816,
            "fundCode": "CBT35F",
            "msLink": "F000005GIT",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=4&investmenttype=1",
            "isActive": "Y",
            "docId": 4,
            "startDate": "2021-01-31T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Annual Report",
            "modifiedDate": "2021-12-31T16:40:01"
        },
        {
            "msId": 10817,
            "fundCode": "CBT35F",
            "msLink": "F000005GIT",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=5&investmenttype=1",
            "isActive": "Y",
            "docId": 5,
            "startDate": "2021-07-31T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Semi-Annual Report",
            "modifiedDate": "2021-12-31T16:40:01"
        },
        {
            "msId": 10818,
            "fundCode": "CBT35F",
            "msLink": "F000005GIT",
            "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000005GIT&documenttype=52&investmenttype=1",
            "isActive": "Y",
            "docId": 52,
            "startDate": "2021-10-31T00:00:00",
            "endDate": null,
            "createdBy": null,
            "modifiedBy": null,
            "createdDate": null,
            "documentName": "Fact sheet",
            "modifiedDate": "2021-12-31T16:40:01"
        }
    ],
    "fund_code": "CBT35F",
    "risk_rating": "1",
    "minimum_initial_subscription_amount": 10000,
    "maximum_subsequent_subscription_amount": 9999999999,
    "manager_code": "CBT",
    "classHexa": "#B3BE66",
    "minimum_initial_subscription_amount_str": "10,000.00",
    "class_name": "CASH",
    "min_holding": 5000,
    "minimum_subsequent_subscription_amount_str": "1,000.00",
    "current_holding": "N",
    "min_redem_amt": 5000,
    "fund_status": "A",
    "class_seq": 1,
    "maximum_initial_subscription_amount": 9999999999,
    "fund_name": "Cimb Islamic Deposit Fund",
    "one_month_ind": "DOWN",
    "fund_indicator": "I",
    "recommended": 15,
    "manager_name": "Cimb-Principal Asset Management Berhad",
    "three_month": "-0.37",
    "one_month": "-0.37",
    "max_redem_amt": 9999999999,
    "fund_risk_rating": "N",
    "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
    "nav_price": 0.9999,
    "min_switch_amt": 5000,
    "risk_name": "Defensive",
    "product_category": "CASH",
    "minimum_subsequent_subscription_amount": 1000
};
const mockDataArr = [
    {
      "maximum_initial_subscription_amount_str": "9,999,999,999.00",
      "close_date": "11 May 2022",
      "three_month_ind": "DOWN",
      "switch_indicator": "Y",
      "fund_document": [
          {
              "msId": 11019,
              "fundCode": "CBT26F",
              "msLink": "F0000024VO",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
              "isActive": "Y",
              "docId": 1,
              "startDate": "2021-07-01T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Master Prospectus",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11020,
              "fundCode": "CBT26F",
              "msLink": "F0000024VO",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
              "isActive": "Y",
              "docId": 77,
              "startDate": "2021-07-01T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Product Highlight Sheet",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11021,
              "fundCode": "CBT26F",
              "msLink": "F0000024VO",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
              "isActive": "Y",
              "docId": 4,
              "startDate": "2020-11-30T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Annual Report",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11022,
              "fundCode": "CBT26F",
              "msLink": "F0000024VO",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
              "isActive": "Y",
              "docId": 5,
              "startDate": "2021-05-31T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Semi-Annual Report",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11023,
              "fundCode": "CBT26F",
              "msLink": "F0000024VO",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
              "isActive": "Y",
              "docId": 52,
              "startDate": "2021-10-31T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Fact sheet",
              "modifiedDate": "2021-12-31T16:40:01"
          }
      ],
      "fund_code": "CBT26F",
      "risk_rating": "1",
      "minimum_initial_subscription_amount": 10000,
      "maximum_subsequent_subscription_amount": 9999999999,
      "manager_code": "CBT",
      "classHexa": "#B3BE66",
      "minimum_initial_subscription_amount_str": "10,000.00",
      "class_name": "CASH",
      "min_holding": 5000,
      "minimum_subsequent_subscription_amount_str": "1,000.00",
      "current_holding": "Y",
      "min_redem_amt": 1000,
      "fund_status": "I",
      "class_seq": 1,
      "maximum_initial_subscription_amount": 9999999999,
      "fund_name": "Cimb Islamic Money Market Fund",
      "one_month_ind": "EQUAL",
      "fund_indicator": "I",
      "esg_fund" : "Y",
      "recommended": 15,
      "manager_name": "Cimb-Principal Asset Management Berhad",
      "three_month": "-6.73",
      "one_month": "0.00",
      "max_redem_amt": 9999999999,
      "fund_risk_rating": "N",
      "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
      "nav_price": 1.0001,
      "min_switch_amt": 1000,
      "risk_name": "Defensive",
      "product_category": "CASH",
      "minimum_subsequent_subscription_amount": 1000,
      "totalInvestment": 1000,
    },
    {
        "maximum_initial_subscription_amount_str": "999,999,999,999.00",
        "close_date": "21 Mar 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 11054,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-06-25T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11055,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-06-25T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11056,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2021-08-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11057,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-02-28T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11058,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "BHL15F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 999999999999,
        "manager_code": "BHL",
        "classHexa": "#B3BE66",
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 0,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "N",
        "min_redem_amt": 0,
        "fund_status": "SO",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 999999999999,
        "fund_name": "Cimb-Principal Deposit Fund",
        "one_month_ind": "DOWN",
        "fund_indicator": "C",
        "esg_fund" : "Y",
        "recommended": 15,
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "-0.38",
        "one_month": "-0.38",
        "max_redem_amt": 999999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
        "nav_price": 1,
        "min_switch_amt": 0,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000,
        "totalInvestment": 1000
    },
    {
      "maximum_initial_subscription_amount_str": "999,999,999,999.00",
      "close_date": "21 Mar 2022",
      "three_month_ind": "DOWN",
      "switch_indicator": "Y",
      "fund_document": [
          {
              "msId": 11054,
              "fundCode": "BHL15F",
              "msLink": "F000000APG",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
              "isActive": "Y",
              "docId": 1,
              "startDate": "2021-06-25T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Master Prospectus",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11055,
              "fundCode": "BHL15F",
              "msLink": "F000000APG",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
              "isActive": "Y",
              "docId": 77,
              "startDate": "2021-06-25T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Product Highlight Sheet",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11056,
              "fundCode": "BHL15F",
              "msLink": "F000000APG",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
              "isActive": "Y",
              "docId": 4,
              "startDate": "2021-08-31T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Annual Report",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11057,
              "fundCode": "BHL15F",
              "msLink": "F000000APG",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
              "isActive": "Y",
              "docId": 5,
              "startDate": "2021-02-28T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Semi-Annual Report",
              "modifiedDate": "2021-12-31T16:40:01"
          },
          {
              "msId": 11058,
              "fundCode": "BHL15F",
              "msLink": "F000000APG",
              "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
              "isActive": "Y",
              "docId": 52,
              "startDate": "2021-10-31T00:00:00",
              "endDate": null,
              "createdBy": null,
              "modifiedBy": null,
              "createdDate": null,
              "documentName": "Fact sheet",
              "modifiedDate": "2021-12-31T16:40:01"
          }
      ],
      "fund_code": "BHL15F",
      "risk_rating": "1",
      "minimum_initial_subscription_amount": 10000,
      "maximum_subsequent_subscription_amount": 999999999999,
      "manager_code": "BHL",
      "classHexa": "#B3BE66",
      "minimum_initial_subscription_amount_str": "10,000.00",
      "class_name": "CASH",
      "min_holding": 0,
      "minimum_subsequent_subscription_amount_str": "1,000.00",
      "current_holding": "N",
      "min_redem_amt": 0,
      "fund_status": "I",
      "class_seq": 1,
      "maximum_initial_subscription_amount": 999999999999,
      "fund_name": "Cimb-Principal Deposit Fund",
      "one_month_ind": "DOWN",
      "fund_indicator": "C",
      "esg_fund" : "Y",
      "recommended": 15,
      "manager_name": "Cimb-Principal Asset Management Berhad Test",
      "three_month": "-0.38",
      "one_month": "-0.38",
      "max_redem_amt": 999999999999,
      "fund_risk_rating": "N",
      "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
      "nav_price": 1,
      "min_switch_amt": 0,
      "risk_name": "Defensive",
      "product_category": "CASH",
      "minimum_subsequent_subscription_amount": 1000,
      "totalInvestment": 1000,
    },
    {
        "maximum_initial_subscription_amount_str": "999,999,999,999.00",
        "close_date": "21 Mar 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 11054,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-06-25T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11055,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-06-25T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11056,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2021-08-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11057,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-02-28T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11058,
                "fundCode": "BHL15F",
                "msLink": "F000000APG",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "BHL15F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 999999999999,
        "manager_code": "BHL",
        "classHexa": "#B3BE66",
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 0,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "N",
        "min_redem_amt": 0,
        "fund_status": "SOHO",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 999999999999,
        "fund_name": "Cimb-Principal Deposit Fund",
        "one_month_ind": "DOWN",
        "fund_indicator": "C",
        "esg_fund" : "Y",
        "recommended": 15,
        "manager_name": "Cimb-Principal Asset Management Berhad Test",
        "three_month": "-0.38",
        "one_month": "-0.38",
        "max_redem_amt": 999999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
        "nav_price": 1,
        "min_switch_amt": 0,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000,
        "totalInvestment": 1000
    }
];

describe('DialogFundsComponent', () => {
  let component: DialogFundsComponent;
  let fixture: ComponentFixture<DialogFundsComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [MatDialogModule, MatBottomSheetModule, RouterTestingModule, BrowserAnimationsModule, MatSortModule, MatPaginatorModule],
      declarations: [ DialogFundsComponent ],
      providers: [
        { provide: MAT_DIALOG_DATA, useValue: {} },
        { provide: MatDialogRef, useValue: dialogMock }
      ]
    })
    .compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(DialogFundsComponent);
    component = fixture.componentInstance;

    component.fundsArray = mockDataArr;

    fixture.autoDetectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('call for a cancel method', () => {
    expect(component.cancel()).toBeUndefined();
  });
  it('triggers a Nav bottom sheet', () => {
    expect(component.openNavBottomSheet()).toBeUndefined()
  });
  it('triggers a Fund Holiday bottom sheet', () => {
    expect(component.openFundHolidayBottomSheet()).toBeUndefined()
  });
  it('select a fund', () => {
    const obj = fundObj;
    expect(component.onSelect(obj)).toBeUndefined()
  })

  it('filters a selected fund', () => {
    const obj = fundObj;
    const tempArray = [
      {
        "maximum_initial_subscription_amount_str": "9,999,999,999.00",
        "close_date": "11 May 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 11019,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11020,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11021,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2020-11-30T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11022,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-05-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11023,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "CBT26F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 9999999999,
        "manager_code": "CBT",
        "classHexa": "#B3BE66",
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 5000,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "N",
        "min_redem_amt": 1000,
        "fund_status": "A",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 9999999999,
        "fund_name": "Cimb Islamic Money Market Fund",
        "one_month_ind": "EQUAL",
        "fund_indicator": "I",
        "recommended": 15,
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "-6.73",
        "one_month": "0.00",
        "max_redem_amt": 9999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
        "nav_price": 1.0001,
        "min_switch_amt": 1000,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000,
        "totalInvestment": 1000,
      },
      {
          "maximum_initial_subscription_amount_str": "999,999,999,999.00",
          "close_date": "21 Mar 2022",
          "three_month_ind": "DOWN",
          "switch_indicator": "Y",
          "fund_document": [
              {
                  "msId": 11054,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                  "isActive": "Y",
                  "docId": 1,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Master Prospectus",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11055,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                  "isActive": "Y",
                  "docId": 77,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Product Highlight Sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11056,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                  "isActive": "Y",
                  "docId": 4,
                  "startDate": "2021-08-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11057,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                  "isActive": "Y",
                  "docId": 5,
                  "startDate": "2021-02-28T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Semi-Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11058,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                  "isActive": "Y",
                  "docId": 52,
                  "startDate": "2021-10-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Fact sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              }
          ],
          "fund_code": "BHL15F",
          "risk_rating": "1",
          "minimum_initial_subscription_amount": 10000,
          "maximum_subsequent_subscription_amount": 999999999999,
          "manager_code": "BHL",
          "classHexa": "#B3BE66",
          "minimum_initial_subscription_amount_str": "10,000.00",
          "class_name": "CASH",
          "min_holding": 0,
          "minimum_subsequent_subscription_amount_str": "1,000.00",
          "current_holding": "N",
          "min_redem_amt": 0,
          "fund_status": "A",
          "class_seq": 1,
          "maximum_initial_subscription_amount": 999999999999,
          "fund_name": "Cimb-Principal Deposit Fund",
          "one_month_ind": "DOWN",
          "fund_indicator": "C",
          "recommended": 15,
          "manager_name": "Cimb-Principal Asset Management Berhad",
          "three_month": "-0.38",
          "one_month": "-0.38",
          "max_redem_amt": 999999999999,
          "fund_risk_rating": "N",
          "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
          "nav_price": 1,
          "min_switch_amt": 0,
          "risk_name": "Defensive",
          "product_category": "CASH",
          "minimum_subsequent_subscription_amount": 1000,
          "totalInvestment": 1000,
      }
    ];
    fixture.componentInstance;
    component.tableDetails.data = tempArray;
    fixture.detectChanges();

    expect(component.onSelect(obj)).toBeUndefined()
  });

  it('removes item fron list', () => {
    const fund = fundObj;
    const idx = 1;
    expect(component.onRemove(fund, idx)).toBeUndefined()
  });

  it('removes item fron list with condition', () => {
    const fund = fundObj;
    const idx = 1;

    const tempArray = [
        {
          "maximum_initial_subscription_amount_str": "9,999,999,999.00",
          "close_date": "11 May 2022",
          "three_month_ind": "DOWN",
          "switch_indicator": "Y",
          "fund_document": [
              {
                  "msId": 11019,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
                  "isActive": "Y",
                  "docId": 1,
                  "startDate": "2021-07-01T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Master Prospectus",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11020,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
                  "isActive": "Y",
                  "docId": 77,
                  "startDate": "2021-07-01T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Product Highlight Sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11021,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
                  "isActive": "Y",
                  "docId": 4,
                  "startDate": "2020-11-30T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11022,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
                  "isActive": "Y",
                  "docId": 5,
                  "startDate": "2021-05-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Semi-Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11023,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
                  "isActive": "Y",
                  "docId": 52,
                  "startDate": "2021-10-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Fact sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              }
          ],
          "fund_code": "CBT26F",
          "risk_rating": "1",
          "minimum_initial_subscription_amount": 10000,
          "maximum_subsequent_subscription_amount": 9999999999,
          "manager_code": "CBT",
          "classHexa": "#B3BE66",
          "minimum_initial_subscription_amount_str": "10,000.00",
          "class_name": "CASH",
          "min_holding": 5000,
          "minimum_subsequent_subscription_amount_str": "1,000.00",
          "current_holding": "N",
          "min_redem_amt": 1000,
          "fund_status": "A",
          "class_seq": 1,
          "maximum_initial_subscription_amount": 9999999999,
          "fund_name": "Cimb Islamic Money Market Fund",
          "one_month_ind": "EQUAL",
          "fund_indicator": "I",
          "esg_fund" : "Y",
          "recommended": 15,
          "manager_name": "Cimb-Principal Asset Management Berhad",
          "three_month": "-6.73",
          "one_month": "0.00",
          "max_redem_amt": 9999999999,
          "fund_risk_rating": "N",
          "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
          "nav_price": 1.0001,
          "min_switch_amt": 1000,
          "risk_name": "Defensive",
          "product_category": "CASH",
          "minimum_subsequent_subscription_amount": 1000,
          "totalInvestment": 1000,
        },
        {
            "maximum_initial_subscription_amount_str": "999,999,999,999.00",
            "close_date": "21 Mar 2022",
            "three_month_ind": "DOWN",
            "switch_indicator": "Y",
            "fund_document": [
                {
                    "msId": 11054,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                    "isActive": "Y",
                    "docId": 1,
                    "startDate": "2021-06-25T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Master Prospectus",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11055,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                    "isActive": "Y",
                    "docId": 77,
                    "startDate": "2021-06-25T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Product Highlight Sheet",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11056,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                    "isActive": "Y",
                    "docId": 4,
                    "startDate": "2021-08-31T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Annual Report",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11057,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                    "isActive": "Y",
                    "docId": 5,
                    "startDate": "2021-02-28T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Semi-Annual Report",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11058,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                    "isActive": "Y",
                    "docId": 52,
                    "startDate": "2021-10-31T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Fact sheet",
                    "modifiedDate": "2021-12-31T16:40:01"
                }
            ],
            "fund_code": "BHL15F",
            "risk_rating": "1",
            "minimum_initial_subscription_amount": 10000,
            "maximum_subsequent_subscription_amount": 999999999999,
            "manager_code": "BHL",
            "classHexa": "#B3BE66",
            "minimum_initial_subscription_amount_str": "10,000.00",
            "class_name": "CASH",
            "min_holding": 0,
            "minimum_subsequent_subscription_amount_str": "1,000.00",
            "current_holding": "N",
            "min_redem_amt": 0,
            "fund_status": "A",
            "class_seq": 1,
            "maximum_initial_subscription_amount": 999999999999,
            "fund_name": "Cimb-Principal Deposit Fund",
            "one_month_ind": "DOWN",
            "fund_indicator": "C",
            "esg_fund" : "Y",
            "recommended": 15,
            "manager_name": "Cimb-Principal Asset Management Berhad",
            "three_month": "-0.38",
            "one_month": "-0.38",
            "max_redem_amt": 999999999999,
            "fund_risk_rating": "N",
            "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
            "nav_price": 1,
            "min_switch_amt": 0,
            "risk_name": "Defensive",
            "product_category": "CASH",
            "minimum_subsequent_subscription_amount": 1000,
            "totalInvestment": 1000,
        }
    ];

    fixture.componentInstance;
    component.tempArray = tempArray;
    fixture.detectChanges();
    expect(component.onRemove(fund, idx)).toBeUndefined()
  });


  it('push the deleted item to the array', () => {
    const fund = fundObj;
    const idx = 1;

    const tempArray = [
        {
          "maximum_initial_subscription_amount_str": "9,999,999,999.00",
          "close_date": "11 May 2022",
          "three_month_ind": "DOWN",
          "switch_indicator": "Y",
          "fund_document": [
              {
                  "msId": 11019,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
                  "isActive": "Y",
                  "docId": 1,
                  "startDate": "2021-07-01T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Master Prospectus",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11020,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
                  "isActive": "Y",
                  "docId": 77,
                  "startDate": "2021-07-01T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Product Highlight Sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11021,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
                  "isActive": "Y",
                  "docId": 4,
                  "startDate": "2020-11-30T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11022,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
                  "isActive": "Y",
                  "docId": 5,
                  "startDate": "2021-05-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Semi-Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11023,
                  "fundCode": "CBT26F",
                  "msLink": "F0000024VO",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
                  "isActive": "Y",
                  "docId": 52,
                  "startDate": "2021-10-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Fact sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              }
          ],
          "fund_code": "CBT26F",
          "risk_rating": "1",
          "minimum_initial_subscription_amount": 10000,
          "maximum_subsequent_subscription_amount": 9999999999,
          "manager_code": "CBT",
          "classHexa": "#B3BE66",
          "minimum_initial_subscription_amount_str": "10,000.00",
          "class_name": "CASH",
          "min_holding": 5000,
          "minimum_subsequent_subscription_amount_str": "1,000.00",
          "current_holding": "N",
          "min_redem_amt": 1000,
          "fund_status": "A",
          "class_seq": 1,
          "maximum_initial_subscription_amount": 9999999999,
          "fund_name": "Cimb Islamic Money Market Fund",
          "one_month_ind": "EQUAL",
          "fund_indicator": "I",
          "esg_fund" : "Y",
          "recommended": 15,
          "manager_name": "Cimb-Principal Asset Management Berhad",
          "three_month": "-6.73",
          "one_month": "0.00",
          "max_redem_amt": 9999999999,
          "fund_risk_rating": "N",
          "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
          "nav_price": 1.0001,
          "min_switch_amt": 1000,
          "risk_name": "Defensive",
          "product_category": "CASH",
          "minimum_subsequent_subscription_amount": 1000,
          "totalInvestment": 1000,
        },
        {
            "maximum_initial_subscription_amount_str": "999,999,999,999.00",
            "close_date": "21 Mar 2022",
            "three_month_ind": "DOWN",
            "switch_indicator": "Y",
            "fund_document": [
                {
                    "msId": 11054,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                    "isActive": "Y",
                    "docId": 1,
                    "startDate": "2021-06-25T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Master Prospectus",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11055,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                    "isActive": "Y",
                    "docId": 77,
                    "startDate": "2021-06-25T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Product Highlight Sheet",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11056,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                    "isActive": "Y",
                    "docId": 4,
                    "startDate": "2021-08-31T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Annual Report",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11057,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                    "isActive": "Y",
                    "docId": 5,
                    "startDate": "2021-02-28T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Semi-Annual Report",
                    "modifiedDate": "2021-12-31T16:40:01"
                },
                {
                    "msId": 11058,
                    "fundCode": "BHL15F",
                    "msLink": "F000000APG",
                    "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                    "isActive": "Y",
                    "docId": 52,
                    "startDate": "2021-10-31T00:00:00",
                    "endDate": null,
                    "createdBy": null,
                    "modifiedBy": null,
                    "createdDate": null,
                    "documentName": "Fact sheet",
                    "modifiedDate": "2021-12-31T16:40:01"
                }
            ],
            "fund_code": "BHL15F",
            "risk_rating": "1",
            "minimum_initial_subscription_amount": 10000,
            "maximum_subsequent_subscription_amount": 999999999999,
            "manager_code": "BHL",
            "classHexa": "#B3BE66",
            "minimum_initial_subscription_amount_str": "10,000.00",
            "class_name": "CASH",
            "min_holding": 0,
            "minimum_subsequent_subscription_amount_str": "1,000.00",
            "current_holding": "N",
            "min_redem_amt": 0,
            "fund_status": "A",
            "class_seq": 1,
            "maximum_initial_subscription_amount": 999999999999,
            "fund_name": "Cimb-Principal Deposit Fund",
            "one_month_ind": "DOWN",
            "fund_indicator": "C",
            "esg_fund" : "Y",
            "recommended": 15,
            "manager_name": "Cimb-Principal Asset Management Berhad",
            "three_month": "-0.38",
            "one_month": "-0.38",
            "max_redem_amt": 999999999999,
            "fund_risk_rating": "N",
            "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
            "nav_price": 1,
            "min_switch_amt": 0,
            "risk_name": "Defensive",
            "product_category": "CASH",
            "minimum_subsequent_subscription_amount": 1000,
            "totalInvestment": 1000,
        }
    ];

    fixture.componentInstance;
    component.tempArray = tempArray;

    const removeitm  = component.tempArray.splice(0, 1);

    component.fundData = removeitm;

    fixture.detectChanges();
    expect(component.fundData).toBeTruthy();
    expect(component.onRemove(fund, idx)).toBeUndefined()
  });

  it('filters by fund status on success path', () => {
    const event = {checked: true};
    const tempArray = [
      {
        "maximum_initial_subscription_amount_str": "9,999,999,999.00",
        "close_date": "11 May 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 11019,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11020,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11021,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2020-11-30T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11022,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-05-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11023,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "CBT26F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 9999999999,
        "manager_code": "CBT",
        "classHexa": "#B3BE66",
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 5000,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "N",
        "min_redem_amt": 1000,
        "fund_status": "A",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 9999999999,
        "fund_name": "Cimb Islamic Money Market Fund",
        "one_month_ind": "EQUAL",
        "fund_indicator": "I",
        "recommended": 15,
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "-6.73",
        "one_month": "0.00",
        "max_redem_amt": 9999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
        "nav_price": 1.0001,
        "min_switch_amt": 1000,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000
      },
      {
          "maximum_initial_subscription_amount_str": "999,999,999,999.00",
          "close_date": "21 Mar 2022",
          "three_month_ind": "DOWN",
          "switch_indicator": "Y",
          "fund_document": [
              {
                  "msId": 11054,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                  "isActive": "Y",
                  "docId": 1,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Master Prospectus",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11055,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                  "isActive": "Y",
                  "docId": 77,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Product Highlight Sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11056,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                  "isActive": "Y",
                  "docId": 4,
                  "startDate": "2021-08-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11057,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                  "isActive": "Y",
                  "docId": 5,
                  "startDate": "2021-02-28T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Semi-Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11058,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                  "isActive": "Y",
                  "docId": 52,
                  "startDate": "2021-10-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Fact sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              }
          ],
          "fund_code": "BHL15F",
          "risk_rating": "1",
          "minimum_initial_subscription_amount": 10000,
          "maximum_subsequent_subscription_amount": 999999999999,
          "manager_code": "BHL",
          "classHexa": "#B3BE66",
          "minimum_initial_subscription_amount_str": "10,000.00",
          "class_name": "CASH",
          "min_holding": 0,
          "minimum_subsequent_subscription_amount_str": "1,000.00",
          "current_holding": "N",
          "min_redem_amt": 0,
          "fund_status": "A",
          "class_seq": 1,
          "maximum_initial_subscription_amount": 999999999999,
          "fund_name": "Cimb-Principal Deposit Fund",
          "one_month_ind": "DOWN",
          "fund_indicator": "C",
          "recommended": 15,
          "manager_name": "Cimb-Principal Asset Management Berhad",
          "three_month": "-0.38",
          "one_month": "-0.38",
          "max_redem_amt": 999999999999,
          "fund_risk_rating": "N",
          "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
          "nav_price": 1,
          "min_switch_amt": 0,
          "risk_name": "Defensive",
          "product_category": "CASH",
          "minimum_subsequent_subscription_amount": 1000
      }
    ];
    component.tableDetails.data = tempArray;
    component.filterByShariah(event)
    
  });

  it('filters by fund status on fail path', () => {
    const event = {checked: false};
    expect(component.filterByShariah(event)).toBeUndefined();
  });

  it('filter fund by focus status', () => {
    const event = {checked: true};
    const tempArray = [
      {
        "maximum_initial_subscription_amount_str": "9,999,999,999.00",
        "close_date": "11 May 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 11019,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11020,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11021,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2020-11-30T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11022,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-05-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11023,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "CBT26F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 9999999999,
        "manager_code": "CBT",
        "classHexa": "#B3BE66",
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 5000,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "Y",
        "min_redem_amt": 1000,
        "fund_status": "A",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 9999999999,
        "fund_name": "Cimb Islamic Money Market Fund",
        "one_month_ind": "EQUAL",
        "fund_indicator": "I",
        "recommended": 15,
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "-6.73",
        "one_month": "0.00",
        "max_redem_amt": 9999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
        "nav_price": 1.0001,
        "min_switch_amt": 1000,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000
      },
      {
          "maximum_initial_subscription_amount_str": "999,999,999,999.00",
          "close_date": "21 Mar 2022",
          "three_month_ind": "DOWN",
          "switch_indicator": "Y",
          "fund_document": [
              {
                  "msId": 11054,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                  "isActive": "Y",
                  "docId": 1,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Master Prospectus",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11055,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                  "isActive": "Y",
                  "docId": 77,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Product Highlight Sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11056,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                  "isActive": "Y",
                  "docId": 4,
                  "startDate": "2021-08-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11057,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                  "isActive": "Y",
                  "docId": 5,
                  "startDate": "2021-02-28T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Semi-Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11058,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                  "isActive": "Y",
                  "docId": 52,
                  "startDate": "2021-10-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Fact sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              }
          ],
          "fund_code": "BHL15F",
          "risk_rating": "1",
          "minimum_initial_subscription_amount": 10000,
          "maximum_subsequent_subscription_amount": 999999999999,
          "manager_code": "BHL",
          "classHexa": "#B3BE66",
          "minimum_initial_subscription_amount_str": "10,000.00",
          "class_name": "CASH",
          "min_holding": 0,
          "minimum_subsequent_subscription_amount_str": "1,000.00",
          "current_holding": "N",
          "min_redem_amt": 0,
          "fund_status": "A",
          "class_seq": 1,
          "maximum_initial_subscription_amount": 999999999999,
          "fund_name": "Cimb-Principal Deposit Fund",
          "one_month_ind": "DOWN",
          "fund_indicator": "C",
          "recommended": 15,
          "manager_name": "Cimb-Principal Asset Management Berhad",
          "three_month": "-0.38",
          "one_month": "-0.38",
          "max_redem_amt": 999999999999,
          "fund_risk_rating": "N",
          "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
          "nav_price": 1,
          "min_switch_amt": 0,
          "risk_name": "Defensive",
          "product_category": "CASH",
          "minimum_subsequent_subscription_amount": 1000
      }
    ];
    component.tableDetails.data = tempArray;

  });

  it('filter fund by focus status', () => {
    const event = {checked: false};
    const tempArray = [
      {
        "maximum_initial_subscription_amount_str": "9,999,999,999.00",
        "close_date": "11 May 2022",
        "three_month_ind": "DOWN",
        "switch_indicator": "Y",
        "fund_document": [
            {
                "msId": 11019,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=1&investmenttype=1",
                "isActive": "Y",
                "docId": 1,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Master Prospectus",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11020,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=77&investmenttype=1",
                "isActive": "Y",
                "docId": 77,
                "startDate": "2021-07-01T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Product Highlight Sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11021,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=4&investmenttype=1",
                "isActive": "Y",
                "docId": 4,
                "startDate": "2020-11-30T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11022,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=5&investmenttype=1",
                "isActive": "Y",
                "docId": 5,
                "startDate": "2021-05-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Semi-Annual Report",
                "modifiedDate": "2021-12-31T16:40:01"
            },
            {
                "msId": 11023,
                "fundCode": "CBT26F",
                "msLink": "F0000024VO",
                "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F0000024VO&documenttype=52&investmenttype=1",
                "isActive": "Y",
                "docId": 52,
                "startDate": "2021-10-31T00:00:00",
                "endDate": null,
                "createdBy": null,
                "modifiedBy": null,
                "createdDate": null,
                "documentName": "Fact sheet",
                "modifiedDate": "2021-12-31T16:40:01"
            }
        ],
        "fund_code": "CBT26F",
        "risk_rating": "1",
        "minimum_initial_subscription_amount": 10000,
        "maximum_subsequent_subscription_amount": 9999999999,
        "manager_code": "CBT",
        "classHexa": "#B3BE66",
        "minimum_initial_subscription_amount_str": "10,000.00",
        "class_name": "CASH",
        "min_holding": 5000,
        "minimum_subsequent_subscription_amount_str": "1,000.00",
        "current_holding": "Y",
        "min_redem_amt": 1000,
        "fund_status": "A",
        "class_seq": 1,
        "maximum_initial_subscription_amount": 9999999999,
        "fund_name": "Cimb Islamic Money Market Fund",
        "one_month_ind": "EQUAL",
        "fund_indicator": "I",
        "recommended": 15,
        "manager_name": "Cimb-Principal Asset Management Berhad",
        "three_month": "-6.73",
        "one_month": "0.00",
        "max_redem_amt": 9999999999,
        "fund_risk_rating": "N",
        "maximum_subsequent_subscription_amount_str": "9,999,999,999.00",
        "nav_price": 1.0001,
        "min_switch_amt": 1000,
        "risk_name": "Defensive",
        "product_category": "CASH",
        "minimum_subsequent_subscription_amount": 1000
      },
      {
          "maximum_initial_subscription_amount_str": "999,999,999,999.00",
          "close_date": "21 Mar 2022",
          "three_month_ind": "DOWN",
          "switch_indicator": "Y",
          "fund_document": [
              {
                  "msId": 11054,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=1&investmenttype=1",
                  "isActive": "Y",
                  "docId": 1,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Master Prospectus",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11055,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=77&investmenttype=1",
                  "isActive": "Y",
                  "docId": 77,
                  "startDate": "2021-06-25T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Product Highlight Sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11056,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=4&investmenttype=1",
                  "isActive": "Y",
                  "docId": 4,
                  "startDate": "2021-08-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11057,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=5&investmenttype=1",
                  "isActive": "Y",
                  "docId": 5,
                  "startDate": "2021-02-28T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Semi-Annual Report",
                  "modifiedDate": "2021-12-31T16:40:01"
              },
              {
                  "msId": 11058,
                  "fundCode": "BHL15F",
                  "msLink": "F000000APG",
                  "msUrl": "https://doc.morningstar.com/LatestDoc.aspx?clientid=cimbmsia&key=0f3db24a72f03156&language=451&investmentid=F000000APG&documenttype=52&investmenttype=1",
                  "isActive": "Y",
                  "docId": 52,
                  "startDate": "2021-10-31T00:00:00",
                  "endDate": null,
                  "createdBy": null,
                  "modifiedBy": null,
                  "createdDate": null,
                  "documentName": "Fact sheet",
                  "modifiedDate": "2021-12-31T16:40:01"
              }
          ],
          "fund_code": "BHL15F",
          "risk_rating": "1",
          "minimum_initial_subscription_amount": 10000,
          "maximum_subsequent_subscription_amount": 999999999999,
          "manager_code": "BHL",
          "classHexa": "#B3BE66",
          "minimum_initial_subscription_amount_str": "10,000.00",
          "class_name": "CASH",
          "min_holding": 0,
          "minimum_subsequent_subscription_amount_str": "1,000.00",
          "current_holding": "N",
          "min_redem_amt": 0,
          "fund_status": "A",
          "class_seq": 1,
          "maximum_initial_subscription_amount": 999999999999,
          "fund_name": "Cimb-Principal Deposit Fund",
          "one_month_ind": "DOWN",
          "fund_indicator": "C",
          "recommended": 15,
          "manager_name": "Cimb-Principal Asset Management Berhad",
          "three_month": "-0.38",
          "one_month": "-0.38",
          "max_redem_amt": 999999999999,
          "fund_risk_rating": "N",
          "maximum_subsequent_subscription_amount_str": "999,999,999,999.00",
          "nav_price": 1,
          "min_switch_amt": 0,
          "risk_name": "Defensive",
          "product_category": "CASH",
          "minimum_subsequent_subscription_amount": 1000
      }
    ];
    component.tableDetails.data = tempArray;

  });

  it('calls for initialization fn', () => {
    fixture.componentInstance;
    component.fundsArray = mockDataArr;
    fixture.detectChanges();
    expect(component.initialization()).toBeUndefined();
  });

  it('filters funds array', () => {
    expect(component.filterFunds(mockDataArr)).toBeUndefined()
  })

  it('sorts funds array', () => {
    expect(component.sortFunds(mockDataArr)).toBeUndefined()
  });

  it('shuld call applyFilters()', () => {
    component.applyFilters()
  });

  it('initially sets up sorting', () => {
    fixture.componentInstance;
    component.tableDetails.data = mockDataArr;
    fixture.detectChanges();
 
    expect(component.sortColumnByProperty()).toBeUndefined()
  });

});
