export const path = {
    ASNB_DASHBOARD: 'asnb-dashboard',
    AVAILABLE_FUND: 'available-funds',
    GETTING_STARTED: 'getting-started',
    DASHBOARD: 'dashboard',
    RISK_PROFILE_QUESTIONS: 'risk-profile/questions',
    RISK_PROFILE_RESULTS: 'risk-profile/results',
    REDIRECT_TO_CLICKS: 'RedirectToClicks',
    PORTFOLIO_RECOMMENDATION: 'portfolio-recommendation',
    INVESTMENT_OPTION: 'investment-options',
    TRANSACTION_LOGOUT: 'TransactionLogout',
    OPENING_ACCOUNT: 'opening-account',
    WEALTH_DASHBOARD: 'wealthdashboard',
    CART_COMPONENTS: 'cart',
    PAGE_NOT_FOUND: 'pageNotFound',
    MAINTENANCE: 'maintenance',
    LOGOUT: 'Logout',
    CIMBCLICKS: 'https://www.cimbclicks.com.my',
};
