import { User } from '../../model/user.model';
import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class DashbordService {

  // getAccountDetailUrl =
  //   'https://wld.devapps.tcjteam.tech/api/demo/account/getAccountDetail/';
  dashbordUserData: User;
  dashbordData = 1;
  customer_id = '';
  customer_id_type = '';
  debit_card_no = '';
  riskProfileData = {
    riskProfile: 'Aggressive',
    riskProfileDescription:
      'I want to receive high capital growth and I am willing to accept the risk of losing my capital.',
    riskProfileRedoAllowed: true,
  };
  totalReturnsGainOrLoss = true;
  totalReturnsAmount = '2.61';
  totalReturnsPercentage = '6.93%';
  totalReturnsvalue = 'TOTAL GAIN / LOSS';
  totalReturnsToolTip =
    'These are the gains or losses on your investments. It is calculated by subtracting the Total Invested from Current Investment Value.';

  currentInverstmentCurrency = 'MYR';
  currentInverstmentAmount = '22,061.61';
  currentInverstmentvalue = 'CURRENT INVESTMENT VALUE';
  currentInverstmentToolTip =
    'This equals your total amount invested plus your total returns. It represents the current worth of all your funds combined.';

  totalInvestedCurrency = 'MYR';
  totalInvestedAmount = '20,632.50';
  totalInvestedvalue = 'TOTAL INVESTED';
  portfolioWarningMaessage =
    'Your portfolio has changed moderately (10-20%) from the recommended model asset class breakdown. This may result in returns that are different from those expected for your risk profile.s';
    soleprop_ind = "";

    //JSON VERSION 8 fund_list, //My holdings list to display in dashboard page

  fund_list = [
    {
        min_sub_amt : "500",
        current_investment :  "10716.03" ,
        unit_held :  10716.03,
        total_percentage :  "-2.58%" ,
        account_status :  "A" ,
        min_init_amt : "500",
        total_return :  "-283.97" ,
        holding :  "10716.03" ,
        max_sub_amt : "5000",
        joint_indicator :  "01" ,
        average_nav_price : "0.5500",
        classHexa :  "#5CD3CD" ,
        sales_charge : "0.90",
        class_holding : "59.4",
        min_holding : "1000",
        wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
        asset_class :  "LOCAL EQUITY" ,
        fund_status :  "I" ,
        class_seq : "3",
        fund_name :  "AMITTIKAL NEW SDBN" ,
        ut_account_no : " A80111993" ,
        total_invested :  "11000.00" ,
        max_init_amt : "5000",
        syariah_complaint :  "I" ,
        nav_price :  "1.00" ,
        wholesale_ind :  "N",
        fundImg : "./assets/images/chart-decrease.svg",
        fundPosition : "Increase",
        risk_ind: "N",
        risk_name: "DEFENSIVE",
        min_amt: 500.00,
        max_amt: 1200.00,

    },
    {
        min_sub_amt : "500",
        current_investment :  "1995.53" ,
        unit_held :  1995.53 ,
        total_percentage :  "42.54%" ,
        account_status :  "A" ,
        min_init_amt : "500",
        total_return :  "+595.53" ,
        holding :  "1995.53" ,
        max_sub_amt : "6000",
        joint_indicator :  "01" ,
        average_nav_price : "0.5500",
        classHexa :  "#D45DBA" ,
        sales_charge : "0.50",
        class_holding : "15.8",
        min_holding : "1000",
        wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
        asset_class :  "GLOBAL EQUITY" ,
        fund_status :  "A" ,
        class_seq : "5",
        fund_name :  "AMPAN EUROPEAN PROPERTY EQUITIES" ,
        ut_account_no :  "A80111993" ,
        total_invested :  "1400.00" ,
        max_init_amt : "6000",
        syariah_complaint :  "C" ,
        nav_price :  "1.00" ,
        wholesale_ind :  "N",
        fundImg : "./assets/images/chart-increase.svg",
        fundPosition : "Increase",
        risk_ind: "N",
        risk_name: "CONSERVATIVE",
        min_amt: 500.00,
        max_amt: 1200.00,
    },
    {
      min_sub_amt : "500",
      current_investment :  "10716.03" ,
      unit_held :  10716.03 ,
      total_percentage :  "-2.58%" ,
      account_status :  "A" ,
      min_init_amt : "500",
      total_return :  "-283.97" ,
      holding :  "10,716.03" ,
      max_sub_amt : "7000",
      joint_indicator :  "01" ,
      average_nav_price : "0.5500",
      classHexa :  "#5CD3CD" ,
      sales_charge : "0.70",
      class_holding : "59.4",
      min_holding : "1000",
      wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
      asset_class :  "GLOBAL EQUITY" ,
      fund_status :  "A" ,
      class_seq : "5",
      fund_name :  "WHOLESALES AMITTIKAL" ,
      ut_account_no : " A80111993" ,
      total_invested :  "11000.00" ,
      max_init_amt :  "1200",
      syariah_complaint :  "C" ,
      nav_price :  "1.00" ,
      fundImg : "./assets/images/chart-decrease.svg",
      fundPosition : "Increase",
      risk_ind: "N",
      risk_name: "BALANCED",
      min_amt: 500.00,
      max_amt: 1200.00,
  },
  {
      min_sub_amt : "500",
      current_investment :  "1995.53" ,
      unit_held :  1995.53 ,
      total_percentage :  "42.54%" ,
      account_status :  "A" ,
      min_init_amt : "1000",
      total_return :  "+595.53" ,
      holding :  "1995.53" ,
      max_sub_amt : 8000,
      joint_indicator :  "01" ,
      average_nav_price : "0.5500",
      classHexa :  "#D45DBA" ,
      sales_charge : "0.10",
      class_holding : "15.8",
      min_holding : "1000",
      wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
      asset_class :  "LOCAL EQUITY" ,
      fund_status :  "A" ,
      class_seq : "3",
      fund_name :  "AMPAN EUROPEAN PROPERTY EQUITIES" ,
      ut_account_no :  "A80111993" ,
      total_invested :  "1400.00" ,
      max_init_amt : "2200",
      syariah_complaint :  "C" ,
      nav_price :  "1.00" ,
      fundImg : "./assets/images/chart-increase.svg",
      fundPosition : "Increase",
      risk_ind: "N",
      risk_name: "GROWTH",
      min_amt: 500.00,
      max_amt: 1200.00,
  },
  {
    min_sub_amt : "500",
    current_investment :  "10716.03" ,
    unit_held :  10716.03 ,
    total_percentage :  "-2.58%" ,
    account_status :  "A" ,
    min_init_amt : 1000,
    total_return :  "-283.97" ,
    holding :  "10716.03" ,
    max_sub_amt : "1200",
    joint_indicator :  "01" ,
    average_nav_price : "0.5500",
    classHexa :  "#5CD3CD" ,
    sales_charge : "0.20",
    class_holding : "59.4",
    min_holding : "1000",
    wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
    asset_class :  "CASH" ,
    fund_status :  "I" ,
    class_seq : "1",
    fund_name :  "SDBN AMITTIKAL" ,
    ut_account_no : " A80111993" ,
    total_invested :  "11000.00" ,
    max_init_amt : "1200",
    syariah_complaint :  "I" ,
    nav_price :  "1.00" ,
    wholesale_ind : "S",
    fundImg : "./assets/images/chart-decrease.svg",
    fundPosition : "Increase",
    risk_ind: "N",
    risk_name: "AGGRESIVE",
    min_amt: 500.00,
    max_amt: 1200.00,
},
{
  min_sub_amt : "500",
  current_investment :  "1071.03" ,
  unit_held :  10716.03 ,
  total_percentage :  "-21.58%" ,
  account_status :  "A" ,
  min_init_amt : "1000",
  total_return :  "-2,831.97" ,
  holding :  "10716.03" ,
  max_sub_amt : "1200",
  joint_indicator :  "01" ,
  average_nav_price : "0.5500",
  classHexa :  "#5CD3CD" ,
  sales_charge : "0.50",
  class_holding : "59.4",
  min_holding : "1000",
  wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
  asset_class :  "CASH" ,
  fund_status :  "I" ,
  class_seq : "1",
  fund_name :  "Principal Deposit" ,
  ut_account_no : " A80111993" ,
  total_invested :  "11000.00" ,
  max_init_amt : "1200",
  syariah_complaint :  "I" ,
  nav_price :  "1.00" ,
  wholesale_ind : "S",
  fundImg : "./assets/images/chart-decrease.svg",
  fundPosition : "Increase",
  risk_ind: "N",
  risk_name: "DEFENSIVE",
  min_amt: 500.00,
  max_amt: 1200.00,
},
{
    min_sub_amt : "1000",
    current_investment :  "1995.53" ,
    unit_held :  1995.53 ,
    total_percentage :  "42.54%" ,
    account_status :  "A" ,
    min_init_amt : "1000",
    total_return :  "+5,954.53" ,
    holding :  "1995.53" ,
    max_sub_amt : "12000",
    joint_indicator :  "01" ,
    average_nav_price : "0.5500",
    classHexa :  "#D45DBA" ,
    sales_charge : "0.40",
    class_holding : "15.8",
    min_holding : "1000",
    wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
    asset_class :  "CASH" ,
    fund_status :  "A" ,
    class_seq : "1",
    fund_name :  "AMPAN EUROPEAN PROPERTY EQUITIES" ,
    ut_account_no :  "A80111993" ,
    total_invested :  "1400.00" ,
    max_init_amt :  "3200",
    syariah_complaint :  "C" ,
    nav_price :  "1.00" ,
    wholesale_ind : "N",
    fundImg : "./assets/images/chart-increase.svg",
    fundPosition : "Increase",
    risk_ind: "Y",
    risk_name: "AGGRESIVE",
    min_amt: 500.00,
    max_amt: 1200.00,
},
{
  min_sub_amt: "200",
  current_investment: "5061.66",
  wholesale_msg: "Wholesales Msg Fund Detail Object Found",
  unit_held: 9203.01,
  asset_class: "REGIONAL EQUITY",
  fund_status: "A",
  class_seq: "4",
  total_percentage: "1.23%",
  fund_name: "PRINCIPAL GREATER CHINA EQUITY FUND (FKA CIMB-PRINCIPAL GREATER CHINA EQUITY FUND)",
  ut_account_no: "A80111764",
  total_invested: 5000.00,
  min_init_amt: "500",
  total_return: "+61.66",
  holding: "9,203.01",
  max_sub_amt:  "1200",
  average_nav_price: "0.5500",
  max_init_amt:  "1200",
  classHexa: "#955CD6",
  syariah_complaint: "C",
  nav_price: "0.56",
  sales_charge: "0.40",
  wholesale_ind: "N",
  class_holding: "58",
  min_holding: "500",
  fundImg : "./assets/images/chart-increase.svg",
  risk_ind: "N",
  risk_name: "CONSERVATIVE",
  min_amt: 500.00,
  max_amt: 1200.00,
}, {
  min_sub_amt: "200",
  current_investment: "519.40",
  wholesale_msg: "Wholesales Msg Fund Detail Object Found",
  unit_held: 1000.00,
  asset_class: "REGIONAL EQUITY",
  fund_status: "A",
  class_seq: "4",
  total_percentage: "-48.06%",
  fund_name: "PRINCIPAL ISLAMIC ASIA PACIFIC DYNAMIC EQUITY FUND (FKA CIMB ISLAMIC ASIA PACIFIC EQUITY FUND)",
  ut_account_no: "A80113215",
  total_invested: "1000.00",
  min_init_amt: "500",
  total_return: "-480.60",
  holding: "1,000.00",
  max_sub_amt:  "1200",
  average_nav_price: "0.5194",
  max_init_amt:  "1200",
  classHexa: "#955CD6",
  syariah_complaint: "I",
  nav_price: "0.52",
  sales_charge: "0.33",
  wholesale_ind: "N",
  class_holding: "58",
  min_holding: "0",
  fundImg : "./assets/images/chart-decrease.svg",
  risk_ind: "Y",
  risk_name: "AGGRESIVE",
  min_amt: 500.00,
  max_amt: 1200.00,
},
{
  min_sub_amt : "500",
  current_investment :  "10716.03" ,
  unit_held :  10716.03 ,
  total_percentage :  "-2.58%" ,
  account_status :  "A" ,
  min_init_amt : "500",
  total_return :  "-283.97" ,
  holding :  "10716.03" ,
  max_sub_amt :  "1200",
  joint_indicator :  "01" ,
  average_nav_price : "0.5500",
  classHexa :  "#5CD3CD" ,
  sales_charge : "0.60",
  class_holding : "59.4",
  min_holding : "1000",
  wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
  asset_class :  "FIXED INCOME" ,
  fund_status :  "A" ,
  class_seq : "2",
  fund_name :  "AMITTIKAL" ,
  ut_account_no : " A80111993" ,
  total_invested :  "11000.00" ,
  max_init_amt :  "1200",
  syariah_complaint :  "I" ,
  nav_price :  "1.00" ,
  fundImg : "./assets/images/chart-decrease.svg",
  fundPosition : "Increase",
  risk_ind: "N",
  risk_name: "BALANCED",
  min_amt: 500.00,
  max_amt: 1200.00,
},
{
  min_sub_amt : "500",
  current_investment :  "1995.53" ,
  unit_held :  1995.53,
  total_percentage :  "42.54%" ,
  account_status :  "A" ,
  min_init_amt : "1000",
  total_return :  "+595.53" ,
  holding :  "1,995.53" ,
  max_sub_amt :  "1200",
  joint_indicator :  "01" ,
  average_nav_price : "0.5500",
  classHexa :  "#D45DBA" ,
  sales_charge : "0.10",
  class_holding : "15.8",
  min_holding : "1000",
  wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
  asset_class :  "FIXED INCOME" ,
  fund_status :  "A" ,
  class_seq : "2",
  fund_name :  "AMPAN EUROPEAN PROPERTY EQUITIES" ,
  ut_account_no :  "A80111993" ,
  total_invested :  "1400.00" ,
  max_init_amt :  1300,
  syariah_complaint :  "C" ,
  nav_price :  "1.00" ,
  fundImg : "./assets/images/chart-increase.svg",
  fundPosition : "Increase",
  risk_ind: "N",
  risk_name: "GROWTH",
  min_amt: 500.00,
  max_amt: 1200.00,
},
{
  min_sub_amt : "500",
  current_investment :  "1995.53" ,
  unit_held :  1995.53,
  total_percentage :  "42.54%" ,
  account_status :  "A" ,
  min_init_amt : "1000",
  total_return :  "+595.53" ,
  holding :  "1995.53" ,
  max_sub_amt :  "1200",
  joint_indicator :  "01" ,
  average_nav_price : "0.5500",
  classHexa :  "#D45DBA" ,
  sales_charge : "0.80",
  class_holding : "15.8",
  min_holding : "1000",
  wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
  asset_class :  "ALTERNATIVES" ,
  fund_status :  "A" ,
  class_seq : "6",
  fund_name :  "AMPAN EUROPEAN PROPERTY EQUITIES" ,
  ut_account_no :  "A80111993" ,
  total_invested :  "1400.00" ,
  max_init_amt :  "1600",
  syariah_complaint :  "C" ,
  nav_price :  "1.00" ,
   fundImg : "./assets/images/chart-increase.svg",
  fundPosition : "Increase",
  risk_ind: "Y",
  risk_name: "AGGRESIVE",
  min_amt: 500.00,
  max_amt: 1200.00,
},
{
  min_sub_amt : "500",
  current_investment :  "1995.53" ,
  unit_held :  1995.53,
  total_percentage :  "42.54%" ,
  account_status :  "A" ,
  min_init_amt : "1000",
  total_return :  "+595.53" ,
  holding :  "1995.53" ,
  max_sub_amt :  "1200",
  joint_indicator :  "01" ,
  average_nav_price : "0.5500",
  classHexa :  "#D45DBA" ,
  sales_charge : "0.75",
  class_holding : "15.8",
  min_holding : "1000",
  wholesale_msg :  "Wholesales Msg Fund Detail Object Found" ,
  asset_class :  "ALTERNATIVES" ,
  fund_status :  "SOHO" ,
  class_seq : "6",
  fund_name :  "AMITTIKAL SOHO" ,
  ut_account_no :  "A80111993" ,
  total_invested :  "1400.00" ,
  max_init_amt :  "1200",
  syariah_complaint :  "C" ,
  nav_price :  "1.00" ,
  fundImg : "./assets/images/chart-increase.svg",
  fundPosition : "Increase",
  risk_ind: "N",
  risk_name: "DEFENSIVE",
  min_amt: 500.00,
  max_amt: 1200.00,
},
 ];


  portfolioMyHoldingRecommendData = [
    {
      class: 'CASH',
      name: 'cash',
      description1: '4.5%',
      description2: '40.0%',
    },
    {
      class: 'FIXED_INCOME',
      name: 'Fixed Income',
      description1: '24.3%',
      description2: '23.0%',
    },
    {
      class: 'LOCAL_EQUITY',
      name: 'Local Equity',
      description1: '34.5%',
      description2: '16.0%',
    },
    {
      class: 'REGIONAL_EQUITY',
      name: 'Regional Equity',
      description1: '10.4%',
      description2: '18.0%',
    },
    {
      class: 'GLOBAL_EQUITY',
      name: 'Global Equity',
      description1: '21.3%',
      description2: '3.0%',
    },
    {
      class: 'ALTERNATIVES',
      name: 'Alternatives',
      description1: '5.0%',
      description2: '10.0%',
    },
  ];

  portfolioMyHoldingRecommendChartData = {
    chart: {
      type: 'pie',
      plotBackgroundColor: null,
      plotBorderWidth: 0,
      plotShadow: false,
    },
    credits: {
      enabled: false,
    },
    title: {
      text: '',
    },
    plotOptions: {
      series: {
        point: {
          events: {},
        },
      },
      pie: {
        size: '100%',
        borderWidth: 0,
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
          enabled: false,
        },
        showInLegend: false,
        innerSize: '80%',
      },
    },
    tooltip: {
      valueSuffix: '%',
    },
    series: [
      {
        type: 'pie',
        showInLegend: false,
        name: 'Holdings',
        data: [
          {
            name: 'Cash',
            y: 4.5,
          },
          {
            name: 'Fixed Income',
            y: 24.3,
          },
          {
            name: 'Local Equity',
            y: 34.5,
          },
          {
            name: 'Regional Equity',
            y: 10.4,
          },
          {
            name: 'Global Equity',
            y: 21.3,
          },
          {
            name: 'Alternatives',
            y: 5.0,
          },
        ],
        colors: [
          '#B3BE66',
          '#567DCC',
          '#5CD3CD',
          '#955CD6',
          '#D45DBA',
          '#4FA14F',
        ],
      },
      {
        type: 'pie',
        size: '65%',
        showInLegend: false,
        name: 'Recommended',
        data: [
          {
            name: 'Cash',
            y: 40.0,
          },
          {
            name: 'Fixed Income',
            y: 23.0,
          },
          {
            name: 'Local Equity',
            y: 34.5,
          },
          {
            name: 'Regional Equity',
            y: 18.0,
          },
          {
            name: 'Global Equity',
            y: 3.0,
          },
          {
            name: 'Alternatives',
            y: 10.0,
          },
        ],
        colors: [
          '#B3BE66',
          '#567DCC',
          '#5CD3CD',
          '#955CD6',
          '#D45DBA',
          '#4FA14F',
        ],
      },
    ],
  };

  portfolioChartEmpty = {
    chart: {
      type: 'pie',
      plotBackgroundColor: null,
      plotBorderWidth: 0,
      plotShadow: false,
    },
    credits: {
      enabled: false,
    },
    title: {
      text: '',
    },
    plotOptions: {
      series: {
        point: {
          events: {},
        },
      },
      pie: {
        size: '100%',
        borderWidth: 0,
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
          enabled: false,
        },
        showInLegend: false,
        innerSize: '80%',
      },
    },
    tooltip: {
      valueSuffix: '%',
    },
    series: [
      {
        type: 'pie',
        showInLegend: false,
        name: 'Holdings',
        data: [
          {
            name: '',
            y: 100.0,
          },
        ],
        colors: ['#DDDEDE'],
      },
      {
        type: 'pie',
        size: '65%',
        showInLegend: false,
        name: 'Recommended',
        data: [
          {
            name: '',
            y: 100.0,
          },
        ],
        colors: ['#DDDEDE'],
      },
    ],
  };

  dashboardResponse = {
    "deviation_level": "Significant Deviation",
    "color_list": [
      {
        "classHexa": "#B3BE66"
      },
      {
        "classHexa": "#567DCC"
      },
      {
        "classHexa": "#5CD3CD"
      },
      {
        "classHexa": "#955CD6"
      },
      {
        "classHexa": "#D45DBA"
      },
      {
        "classHexa": "#4FA14F"
      }
    ],
    "current_investment": "15,863.44",
    "deviation_value": "45.00",
    "soleprop_ind": "P",
    "risk_profile": "Aggresive",
    "asset_class": [
      {
        "holding": "4.5",
        "asset_class_name": "Cash",
        "classHexa": "#B3BE66",
        "class_seq": 1,
        "recommended": "3.0"
      },
      {
        "holding": "24.3",
        "asset_class_name": "Fixed Income",
        "classHexa": "#567DCC",
        "class_seq": 2,
        "recommended": "23.0"
      },
      {
        "holding": "34.5",
        "asset_class_name": "Local Equity",
        "classHexa": "#5CD3CD",
        "class_seq": 3,
        "recommended": "40.0"
      },
      {
        "holding": "10.4",
        "asset_class_name": "Regional Equity",
        "classHexa": "#955CD6",
        "class_seq": 4,
        "recommended": "15.0"
      },
      {
        "holding": "21.3",
        "asset_class_name": "Global Equity",
        "classHexa": "#D45DBA",
        "class_seq": 5,
        "recommended": "15.0"
      },
      {
        "holding": "4.5",
        "asset_class_name": "Alternative",
        "classHexa": "#4FA14F",
        "class_seq": 6,
        "recommended": "4.0"
      }
    ],
    "investment_ind": "N",
    "total_percentage": "-4.19",
    "total_invested": "16,558.04",
    "small_investment": "100.00",
    "recommended": [
      {
        "name": "CASH / MONEY MARKET",
        "y": 3.0
      },
      {
        "name": "FIXED INCOME FUND",
        "y": 23.0
      },
      {
        "name": "LOCAL EQUITY",
        "y": 40.0
      },
      {
        "name": "REGIONAL EQUITY",
        "y": 15.0
      },
      {
        "name": "GLOBAL EQUITY",
        "y": 15.0
      },
      {
        "name": "ALTERNATIVE",
        "y": 4.0
      }
    ],
    "total_return": "80.60",
    "holding": [
      {
        "name": "CASH",
        "y": 4.5
      },
      {
        "name": "FIXED INCOME FUND",
        "y": 24.3
      },
      {
        "name": "LOCAL EQUITY",
        "y": 34.5
      },
      {
        "name": "REGIONAL EQUITY",
        "y": 10.4
      },
      {
        "name": "GLOBAL EQUITY",
        "y": 21.3
      },
      {
        "name": "ALTERNATIVE",
        "y": 4.5
      }
    ],
    "fund_list": [
      {
        "min_sub_amt": 200,
        "current_investment": "5061.66",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "9203.01",
        "asset_class": "REGIONAL EQUITY",
        "fund_status": "A",
        "class_seq": 4,
        "total_percentage": "1.23",
        "fund_name": "PRINCIPAL GREATER CHINA EQUITY FUND (FKA CIMB-PRINCIPAL GREATER CHINA EQUITY FUND)",
        "ut_account_no": "A80111764",
        "total_invested": "5000.00",
        "min_init_amt": 500,
        "total_return": "+61.66",
        "holding": "9203.01",
        "max_sub_amt":  1200,
        "average_nav_price": 0.5500,
        "max_init_amt":  1200,
        "classHexa": "#955CD6",
        "syariah_complaint": "C",
        "nav_price": "0.56",
        "wholesale_ind": "N",
        "class_holding": "58.0",
        "min_holding": 500
      },
      {
        "min_sub_amt": 200,
        "current_investment": "3605.36",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "5874.80",
        "asset_class": "LOCAL EQUITY",
        "fund_status": "A",
        "class_seq": 3,
        "total_percentage": "21.45",
        "fund_name": "PRINCIPAL ISLAMIC LIFETIME BALANCED GROWTH FUND (FKA CIMB ISLAMIC BALANCED GROWTH FUND)",
        "ut_account_no": "A80113214",
        "total_invested": "2968.53",
        "min_init_amt": 500,
        "total_return": "+636.83",
        "holding": "5874.80",
        "max_sub_amt":  1200,
        "average_nav_price": 0.613699,
        "max_init_amt":  1200,
        "classHexa": "#5CD3CD",
        "syariah_complaint": "I",
        "nav_price": "0.70",
        "wholesale_ind": "N",
        "class_holding": "42.0",
        "min_holding": 500
      },
      {
        "min_sub_amt": 200,
        "current_investment": "2944.96",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "3681.20",
        "asset_class": "REGIONAL EQUITY",
        "fund_status": "A",
        "class_seq": 4,
        "total_percentage": "47.25",
        "fund_name": "PRINCIPAL CHINA-INDIA-INDONESIA-OPPORTUNITIES FUND (FKA CIMB-P CHINA-INDIA-INDONESIA EQUITY FUND)",
        "ut_account_no": "A80113214",
        "total_invested": "2000.00",
        "min_init_amt": 500,
        "total_return": "+944.96",
        "holding": "3681.20",
        "max_sub_amt": 9999999800000,
        "average_nav_price": 0.8,
        "max_init_amt": 9999999800000,
        "classHexa": "#955CD6",
        "syariah_complaint": "C",
        "nav_price": "0.26",
        "wholesale_ind": "N",
        "class_holding": "58.0",
        "min_holding": 500
      },
      {
        "min_sub_amt": 200,
        "current_investment": "519.40",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "1000.00",
        "asset_class": "REGIONAL EQUITY",
        "fund_status": "A",
        "class_seq": 4,
        "total_percentage": "-48.06",
        "fund_name": "PRINCIPAL ISLAMIC ASIA PACIFIC DYNAMIC EQUITY FUND (FKA CIMB ISLAMIC ASIA PACIFIC EQUITY FUND)",
        "ut_account_no": "A80113215",
        "total_invested": "1000.00",
        "min_init_amt": 500,
        "total_return": "-480.60",
        "holding": "1000.00",
        "max_sub_amt":  1200,
        "average_nav_price": 0.5194,
        "max_init_amt":  1200,
        "classHexa": "#955CD6",
        "syariah_complaint": "I",
        "nav_price": "0.52",
        "wholesale_ind": "N",
        "class_holding": "58.0",
        "min_holding": 0
      },
      {
        "min_sub_amt": 200,
        "current_investment": "324.24",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "1176.47",
        "asset_class": "LOCAL EQUITY",
        "fund_status": "A",
        "class_seq": 3,
        "total_percentage": "-67.58",
        "fund_name": "PRINCIPAL ISLAMIC MALAYSIA OPPORTUNITIES FUND (FKA CIMB ISLAMIC AL-AZZAM EQUITY FUND)",
        "ut_account_no": "A80113215",
        "total_invested": "1000.00",
        "min_init_amt": 500,
        "total_return": "-675.76",
        "holding": "1176.47",
        "max_sub_amt":  1200,
        "average_nav_price": 0.275604,
        "max_init_amt":  1200,
        "classHexa": "#5CD3CD",
        "syariah_complaint": "I",
        "nav_price": "0.63",
        "wholesale_ind": "N",
        "class_holding": "42.0",
        "min_holding": 1000
      },
      {
        "min_sub_amt": 200,
        "current_investment": "311.64",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "600.00",
        "asset_class": "REGIONAL EQUITY",
        "fund_status": "A",
        "class_seq": 4,
        "total_percentage": "-48.06",
        "fund_name": "PRINCIPAL ISLAMIC ASIA PACIFIC DYNAMIC EQUITY FUND (FKA CIMB ISLAMIC ASIA PACIFIC EQUITY FUND)",
        "ut_account_no": "A80113793",
        "total_invested": "600.00",
        "min_init_amt": 500,
        "total_return": "-288.36",
        "holding": "600.00",
        "max_sub_amt":  1200,
        "average_nav_price": 0.5194,
        "max_init_amt":  1200,
        "classHexa": "#955CD6",
        "syariah_complaint": "I",
        "nav_price": "0.52",
        "wholesale_ind": "N",
        "class_holding": "58.0",
        "min_holding": 0
      },
      {
        "min_sub_amt": 200,
        "current_investment": "1201.78",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "1958.26",
        "asset_class": "LOCAL EQUITY",
        "fund_status": "A",
        "class_seq": 3,
        "total_percentage": "21.45",
        "fund_name": "PRINCIPAL ISLAMIC LIFETIME BALANCED GROWTH FUND (FKA CIMB ISLAMIC BALANCED GROWTH FUND)",
        "ut_account_no": "A80113794",
        "total_invested": "989.51",
        "min_init_amt": 500,
        "total_return": "+212.27",
        "holding": "1958.26",
        "max_sub_amt":  1200,
        "average_nav_price": 0.613698,
        "max_init_amt":  1200,
        "classHexa": "#5CD3CD",
        "syariah_complaint": "I",
        "nav_price": "0.70",
        "wholesale_ind": "N",
        "class_holding": "42.0",
        "min_holding": 500
      },
      {
        "min_sub_amt": 200,
        "current_investment": "519.40",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "1000.00",
        "asset_class": "REGIONAL EQUITY",
        "fund_status": "A",
        "class_seq": 4,
        "total_percentage": "-48.06",
        "fund_name": "PRINCIPAL ISLAMIC ASIA PACIFIC DYNAMIC EQUITY FUND (FKA CIMB ISLAMIC ASIA PACIFIC EQUITY FUND)",
        "ut_account_no": "A80113794",
        "total_invested": "1000.00",
        "min_init_amt": 500,
        "total_return": "-480.60",
        "holding": "1000.00",
        "max_sub_amt":  1200,
        "average_nav_price": 0.5194,
        "max_init_amt":  1200,
        "classHexa": "#955CD6",
        "syariah_complaint": "I",
        "nav_price": "0.52",
        "wholesale_ind": "N",
        "class_holding": "58.0",
        "min_holding": 0
      },
      {
        "min_sub_amt": 200,
        "current_investment": "1375.00",
        "wholesale_msg": "Wholesales Msg Fund Detail Object Found",
        "unit_held": "2500.00",
        "asset_class": "LOCAL EQUITY",
        "fund_status": "A",
        "class_seq": 3,
        "total_percentage": "-31.25",
        "fund_name": "PRINCIPAL DALI EQUITY GROWTH FUND (FKA CIMB ISLAMIC DALI EQUITY GROWTH FUND)",
        "ut_account_no": "E00000489",
        "total_invested": "2000.00",
        "min_init_amt": 500,
        "total_return": "-625.00",
        "holding": "2500.00",
        "max_sub_amt":  1200,
        "average_nav_price": 0.55,
        "max_init_amt":  1200,
        "classHexa": "#5CD3CD",
        "syariah_complaint": "I",
        "nav_price": "1.00",
        "wholesale_ind": "N",
        "class_holding": "42.0",
        "min_holding": 250
      }
    ],
    "risk_description": "I want to receive high capital growth and I am willing to accept the risk of losing my capital. ",
    "name": "Ali Amir bin Ahmad",
    "deviation_msg": "Your portfolio has <b>changed considerably (20% or more)</b> from the recommended model asset class breakdown. This may result in returns that are different from those expected fro your risk profile",
    "ut_account": [
      {
        "default_ind": "Y",
        "ut_account_no": "A80113794"
      }
    ],
    "casa_ind": "N",
    "last_update_date": "14 Oct 2021, 10:21 am"
  };

  private setDashboardTabSubject = new Subject<number>();
  setDashboardTab$ = this.setDashboardTabSubject.asObservable();

  //set the subject for setting the dashboard tab value
  setDashboardTab(index: number) {
    this.setDashboardTabSubject.next(index)
  }
}
